### ISSUE TITLE
Câmera Stock fechando.

### ISSUE THREAD

**Issue by KarenNascimento5781** [RicardoGuariento/MIUI-XML-11-BRAZILIAN#17]
Quando selecionado o modo PRO o aplicativo crasha, verificado e não acontecendo quando o sistema está em inglês.

Log do erro.

`java.lang.NumberFormatException: For input string: "-3,7"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
	at java.lang.Float.parseFloat(Float.java:451)
	at com.android.camera.data.data.config.ComponentManuallyEV.reInit(Unknown Source:87)
	at com.android.camera.data.data.config.DataItemConfig.reInitComponent(Unknown Source:91)
	at com.android.camera.data.data.config.SupportedConfigFactory.getSupportedTopConfigs(Unknown Source:34)
	at com.android.camera.fragment.top.FragmentTopConfig.provideAnimateElement(Unknown Source:191)
	at com.android.camera.animation.AnimationComposite.dispose(Unknown Source:83)
	at com.android.camera.fragment.BaseFragmentDelegate.delegateMode(Unknown Source:39)
	at com.android.camera.Camera.onModeSelected(Unknown Source:276)
	at com.android.camera.fragment.bottom.action.FragmentBottomAction.changeModeByNewMode(Unknown Source:222)
	at com.android.camera.fragment.bottom.action.FragmentBottomAction.onModeClicked(Unknown Source:46)
	at com.android.camera.ui.ModeSelectView.onClick(Unknown Source:40)
	at android.view.View.performClick(Unknown Source:17)
	at android.view.View.performClickInternal(Unknown Source:3)
	at android.view.View.access$3100(Unknown Source:0)
	at android.view.View$PerformClick.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loop(Unknown Source:207)
	at android.app.ActivityThread.main(Unknown Source:107)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:274)`

**Comment by RicardoGuariento** [comment]
Oi Karen!

Qual é o modelo do seu aparelho?
Isso acontece na hora que você toca no Modo Pro ou pra bater a foto?
Pergunto, porque testei no meu Mi 9 e não aconteceu nenhum problema  :/

**Comment by KarenNascimento5781** [comment]
É um Redmi note 8.

**Comment by KarenNascimento5781** [comment]
Gravação do erro.

**Comment by KarenNascimento5781** [comment]
Camera funcionando em Inglês, ela também functions perfeitamente e espanhol, porém tbm crasha em Portugues Europeu.
![Screenshot_2019-12-15-16-09-42-300_com android camera](https://user-images.githubusercontent.com/58867598/70867562-8575ea00-1f55-11ea-82ac-31f029d2ecea.jpg)

**Comment by KarenNascimento5781** [comment]
Acho que o problema não está na sua tradução, pois quando eu abri a câmera em inglês, a coloquei em segundo plano, troquei pra português e em seguida restaurei o app ele abriu normal, porém, se eu fecho o app o problema volta...

**Comment by RicardoGuariento** [comment]
Acho que não também! Até porque, é a mesma tradução para todos os aparelhos. Eu até procurei por "-3,7" nas linhas de texto e não tem nada

**Comment by KarenNascimento5781** [comment]
Eu postei no fórum principal. Espero que encontrem a solução.
